import { StyleSheet, Platform, StatusBar, Dimensions } from 'react-native';
import { 
  responsiveWidth, 
  responsiveHeight, 
  responsiveFontSize, 
  responsiveSize,
  getSafeAreaInsets,
  getTouchTargetSize,
  getSpacing,
  getBorderRadius,
  getScreenDimensions
} from '../utils/responsiveUtils';

// Get screen dimensions
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

// Get status bar height for consistent header padding
const getStatusBarHeight = (): number => {
  if (Platform.OS === 'ios') {
    return StatusBar.currentHeight || 44;
  } else {
    return StatusBar.currentHeight || 24;
  }
};

const HEADER_PADDING_TOP = getStatusBarHeight() + 10;
const SAFE_AREA_INSETS = getSafeAreaInsets();

export const globalStyles = StyleSheet.create({
  // Login Screen Styles
  loginContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  loginKeyboardView: {
    flex: 1,
  },
  loginContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: getSpacing(3.75),
    paddingVertical: getSpacing(2),
  },
  loginHeader: {
    alignItems: 'center',
    marginBottom: 40,
  },
  loginTitle: {
    fontSize: responsiveFontSize(32),
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: getSpacing(1),
  },
  loginSubtitle: {
    fontSize: responsiveFontSize(16),
    color: '#7f8c8d',
  },
  loginForm: {
    width: '100%',
  },
  loginInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 16,
    paddingHorizontal: 16,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: '#e1e8ed',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  loginInputIcon: {
    marginRight: 12,
  },
  loginInput: {
    flex: 1,
    fontSize: responsiveFontSize(16),
    color: '#2c3e50',
    paddingVertical: getSpacing(2),
    minHeight: getTouchTargetSize(48),
  },
  loginEyeIcon: {
    padding: 4,
  },
  loginButton: {
    backgroundColor: '#3498db',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 8,
    shadowColor: '#3498db',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  loginButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  loginForgotPassword: {
    alignItems: 'center',
    marginTop: 20,
  },
  loginForgotPasswordText: {
    color: '#3498db',
    fontSize: 16,
  },
  loginMobileNumberDisplay: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 16,
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: '#e1e8ed',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  loginMobileNumberText: {
    fontSize: 16,
    color: '#2c3e50',
    fontWeight: '500',
  },
  loginChangeNumberText: {
    color: '#3498db',
    fontSize: 16,
    fontWeight: '500',
  },
  loginResendContainer: {
    alignItems: 'center',
    marginTop: 20,
  },
  loginTimerText: {
    color: '#7f8c8d',
    fontSize: 16,
  },
  loginResendText: {
    color: '#3498db',
    fontSize: 16,
    fontWeight: '500',
  },

  // Home Screen Styles
  homeContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  homeHeader: {
    backgroundColor: '#3498db',
    paddingTop: SAFE_AREA_INSETS.top + getSpacing(1),
    paddingBottom: getSpacing(2.5),
    paddingHorizontal: getSpacing(2.5),
  },
  homeHeaderBottom: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeContent: {
    flex: 1,
    paddingHorizontal: getSpacing(2.5),
    paddingTop: getSpacing(2.5),
    paddingBottom: SAFE_AREA_INSETS.bottom + getSpacing(2),
  },
  homeMenuGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 30,
  },
  homeMenuCard: {
    width: '48%',
    backgroundColor: '#fff',
    borderRadius: getBorderRadius(12),
    padding: getSpacing(2.5),
    alignItems: 'center',
    marginBottom: getSpacing(2),
    minHeight: getTouchTargetSize(120),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  homeIconContainer: {
    width: responsiveSize(60),
    height: responsiveSize(60),
    borderRadius: responsiveSize(30),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: getSpacing(1.5),
  },
  homeMenuTitle: {
    fontSize: responsiveFontSize(16),
    fontWeight: '600',
    color: '#2c3e50',
    textAlign: 'center',
  },
  homeActionButtons: {
    marginBottom: 20,
  },
  homeActionButton: {
    backgroundColor: '#3498db',
    borderRadius: getBorderRadius(12),
    paddingVertical: getSpacing(2),
    alignItems: 'center',
    marginBottom: getSpacing(1.5),
    minHeight: getTouchTargetSize(48),
    shadowColor: '#3498db',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  homeActionButtonText: {
    color: '#fff',
    fontSize: responsiveFontSize(16),
    fontWeight: '600',
  },
  homeStatusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  homeStatusText: {
    fontSize: 14,
    color: '#2c3e50',
    marginRight: 8,
  },
  homeModalOverlay: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  homeDrawerContainer: {
    flex: 1,
    backgroundColor: '#fff',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 2,
      height: 0,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  homeModalBackdrop: {
    flex: 1,
  },

  // Drawer Styles
  drawerContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  drawerHeader: {
    backgroundColor: '#3498db',
    paddingTop: HEADER_PADDING_TOP,
    paddingBottom: 30,
    paddingHorizontal: 20,
  },
  drawerTimeContainer: {
    marginBottom: 20,
  },
  drawerTimeText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
  },
  drawerUserInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  drawerUserIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  drawerUserDetails: {
    flex: 1,
  },
  drawerUserName: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  drawerPhoneInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  drawerPhoneNumber: {
    color: '#fff',
    fontSize: 14,
    marginLeft: 8,
  },
  drawerMenuContainer: {
    flex: 1,
    paddingTop: 10,
    backgroundColor: '#fff',
  },
  drawerMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  drawerMenuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  drawerIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  drawerMenuText: {
    fontSize: 16,
    color: '#2c3e50',
    fontWeight: '500',
  },
  drawerSeparator: {
    height: 1,
    backgroundColor: '#bdc3c7',
    marginVertical: 20,
    marginHorizontal: 20,
  },
  drawerAppTipsContainer: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    marginBottom: 10,
    backgroundColor: '#fff',
  },
  drawerAppTipsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  drawerAppTipsText: {
    fontSize: 16,
    color: '#2c3e50',
    fontWeight: '600',
    marginLeft: 12,
  },
  drawerDeveloperInfo: {
    paddingHorizontal: 20,
    paddingBottom: 30,
    paddingTop: 20,
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
  },
  drawerDeveloperText: {
    fontSize: 12,
    color: '#7f8c8d',
    marginBottom: 4,
  },
  drawerCompanyName: {
    fontSize: 14,
    color: '#3498db',
    fontWeight: '600',
    marginBottom: 2,
  },
  drawerWebsite: {
    fontSize: 12,
    color: '#3498db',
  },

  // Complaint Screen Styles
  complaintContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  complaintHeader: {
    backgroundColor: '#3498db',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: HEADER_PADDING_TOP,
    paddingBottom: 16,
  },
  complaintBackButton: {
    padding: 8,
  },
  complaintSaveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  complaintSaveText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  complaintContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  complaintFieldContainer: {
    marginBottom: 20,
  },
  complaintFieldLabel: {
    fontSize: 16,
    color: '#2c3e50',
    fontWeight: '500',
    marginBottom: 8,
  },
  complaintDropdownContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e1e8ed',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  complaintDropdownInput: {
    flex: 1,
    fontSize: 16,
    color: '#2c3e50',
  },
  complaintTextInput: {
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e1e8ed',
    paddingVertical: 12,
    fontSize: 16,
    color: '#2c3e50',
  },
  complaintMessageInput: {
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e1e8ed',
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: '#2c3e50',
    textAlignVertical: 'top',
    minHeight: 100,
  },

  // Leave Screen Styles
  leaveTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    flex: 1,
    textAlign: 'center',
    marginHorizontal: 20,
  },
  leaveAddButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
  },
  leaveAddText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 4,
  },
  leaveContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  leaveEmptyText: {
    fontSize: 18,
    color: '#7f8c8d',
    fontWeight: '500',
    marginBottom: 8,
    textAlign: 'center',
  },
  leaveEmptySubtext: {
    fontSize: 14,
    color: '#bdc3c7',
    textAlign: 'center',
    lineHeight: 20,
  },

  // Leave Form Styles
  leaveFormContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
    backgroundColor: '#f8f9fa',
  },
  leaveCheckboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  leaveCheckbox: {
    marginRight: 12,
  },
  leaveCheckboxLabel: {
    fontSize: 16,
    color: '#2c3e50',
    fontWeight: '500',
  },
  leaveFieldContainer: {
    marginBottom: 20,
  },
  leaveFieldLabel: {
    fontSize: 16,
    color: '#2c3e50',
    fontWeight: '500',
    marginBottom: 8,
  },
  leaveDropdownContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e1e8ed',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  leaveDropdownInput: {
    flex: 1,
    fontSize: 16,
    color: '#2c3e50',
  },
  leaveTextInput: {
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e1e8ed',
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: '#2c3e50',
  },
  leaveApplyButton: {
    backgroundColor: '#3498db',
    borderRadius: 8,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 30,
    shadowColor: '#3498db',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  leaveApplyButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },

  // Travelling Screen Styles
  travellingTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    flex: 1,
    textAlign: 'center',
    marginHorizontal: 20,
  },
  travellingAddButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
  },
  travellingAddText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 4,
  },
  travellingContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  travellingEmptyText: {
    fontSize: 18,
    color: '#7f8c8d',
    fontWeight: '500',
    marginBottom: 8,
    textAlign: 'center',
  },
  travellingEmptySubtext: {
    fontSize: 14,
    color: '#bdc3c7',
    textAlign: 'center',
    lineHeight: 20,
  },

  // Travelling Form Styles
  travellingFormContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
    backgroundColor: '#f8f9fa',
  },
  travellingFieldContainer: {
    marginBottom: 20,
  },
  travellingFieldLabel: {
    fontSize: 16,
    color: '#2c3e50',
    fontWeight: '500',
    marginBottom: 8,
  },
  travellingDropdownContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e1e8ed',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  travellingDropdownInput: {
    flex: 1,
    fontSize: 16,
    color: '#2c3e50',
  },
  travellingTextInput: {
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e1e8ed',
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: '#2c3e50',
  },
  travellingApplyButton: {
    backgroundColor: '#3498db',
    borderRadius: 8,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 30,
    shadowColor: '#3498db',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  travellingApplyButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },

  // Updated Travelling Form Styles
  travellingFormInput: {
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: '#2c3e50',
    marginBottom: 16,
  },
  travellingAttachmentLabel: {
    fontSize: 16,
    color: '#2c3e50',
    fontWeight: '500',
    marginBottom: 8,
  },
  travellingChooseFileButton: {
    backgroundColor: '#3498db',
    borderRadius: 8,
    paddingHorizontal: 20,
    paddingVertical: 12,
    alignSelf: 'flex-start',
  },
  travellingChooseFileText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
  },
  travellingSubmitButton: {
    backgroundColor: '#3498db',
    borderRadius: 8,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 30,
    shadowColor: '#3498db',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  travellingSubmitButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },

  // Add Customer Screen Styles
  customerContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  customerHeader: {
    backgroundColor: '#3498db',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: HEADER_PADDING_TOP,
    paddingBottom: 16,
  },
  customerBackButton: {
    padding: 8,
  },
  customerTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  customerContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  customerFieldContainer: {
    marginBottom: 20,
  },
  customerInput: {
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: '#2c3e50',
  },
  customerTextArea: {
    minHeight: 100,
    textAlignVertical: 'top',
  },
  customerSubmitButton: {
    backgroundColor: '#3498db',
    borderRadius: 8,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 30,
    shadowColor: '#3498db',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  customerSubmitButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },

  // Create AMC Screen Styles
  amcContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  amcHeader: {
    backgroundColor: '#3498db',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: HEADER_PADDING_TOP,
    paddingBottom: 16,
  },
  amcBackButton: {
    padding: 8,
  },
  amcTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  amcContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  amcFieldContainer: {
    marginBottom: 20,
  },
  amcSectionLabel: {
    fontSize: 16,
    color: '#2c3e50',
    fontWeight: '500',
    marginBottom: 12,
    textAlign: 'center',
  },
  amcLabel: {
    fontSize: 16,
    color: '#2c3e50',
    fontWeight: '500',
    marginBottom: 8,
  },
  amcDropdownContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  amcDropdownText: {
    fontSize: 16,
    color: '#2c3e50',
    flex: 1,
  },
  amcPlaceholderText: {
    color: '#999',
  },
  amcDropdownList: {
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    marginTop: 4,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  amcDropdownItem: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  amcDropdownItemText: {
    fontSize: 16,
    color: '#2c3e50',
  },
  amcDateRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  amcDateButton: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginHorizontal: 4,
  },
  amcDateButtonText: {
    fontSize: 16,
    color: '#2c3e50',
    textAlign: 'center',
  },
  amcUnderlineInput: {
    fontSize: 16,
    color: '#2c3e50',
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    paddingVertical: 8,
  },
  amcNotesInput: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  amcSubmitButton: {
    backgroundColor: '#3498db',
    borderRadius: 8,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 30,
    shadowColor: '#3498db',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  amcSubmitButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },

  // View Attendance Screen Styles
  attendanceContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  attendanceHeader: {
    backgroundColor: '#3498db',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: HEADER_PADDING_TOP,
    paddingBottom: 16,
  },
  attendanceBackButton: {
    padding: 8,
  },
  attendanceTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  attendanceContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  attendanceCalendarCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  attendanceCalendarNav: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  attendanceMonthYear: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2c3e50',
  },
  attendanceNavRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  attendanceWeeksButton: {
    borderWidth: 1,
    borderColor: '#2c3e50',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 12,
  },
  attendanceWeeksButtonText: {
    fontSize: 14,
    color: '#2c3e50',
    fontWeight: '500',
  },
  attendanceWeekDays: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 10,
  },
  attendanceWeekDayText: {
    fontSize: 14,
    color: '#7f8c8d',
    fontWeight: '500',
    width: 40,
    textAlign: 'center',
  },
  attendanceCalendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
  },
  attendanceCalendarDay: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 2,
    borderRadius: 20,
  },
  attendanceCalendarDayInactive: {
    opacity: 0.3,
  },
  attendanceCalendarDaySelected: {
    backgroundColor: '#3498db',
  },
  attendanceCalendarDayText: {
    fontSize: 16,
    color: '#2c3e50',
    fontWeight: '500',
  },
  attendanceCalendarDayTextInactive: {
    color: '#bdc3c7',
  },
  attendanceCalendarDayTextSelected: {
    color: '#fff',
    fontWeight: 'bold',
  },
  attendanceSummaryCard: {
    backgroundColor: '#34495e',
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  attendanceSummaryTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    marginBottom: 20,
  },
  attendanceLegend: {
    marginBottom: 20,
  },
  attendanceLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  attendanceLegendCircle: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 12,
  },
  attendanceLegendText: {
    flex: 1,
    fontSize: 14,
    color: '#ecf0f1',
  },
  attendanceLegendCount: {
    fontSize: 14,
    color: '#ecf0f1',
    fontWeight: 'bold',
    minWidth: 20,
    textAlign: 'right',
  },
  attendanceChartContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 200,
  },
  attendanceChartPlaceholder: {
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: '#2c3e50',
    justifyContent: 'center',
    alignItems: 'center',
  },
  attendanceChartPlaceholderText: {
    fontSize: 12,
    color: '#bdc3c7',
    marginTop: 8,
    textAlign: 'center',
  },

  // Tips Modal Styles
  tipsModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  tipsModalContainer: {
    backgroundColor: '#fff',
    borderRadius: 16,
    width: '100%',
    maxWidth: 400,
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  tipsModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  tipsModalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2c3e50',
  },
  tipsLanguageSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e1e8ed',
  },
  tipsLanguageText: {
    fontSize: 14,
    color: '#2c3e50',
    marginRight: 8,
  },
  tipsModalContent: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    maxHeight: 400,
  },
  tipsModalTipItem: {
    marginBottom: 16,
  },
  tipsModalTipNumber: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: 4,
  },
  tipsModalTipContent: {
    fontSize: 14,
    color: '#34495e',
    lineHeight: 20,
  },
  tipsModalFooter: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
    alignItems: 'flex-end',
  },
  tipsModalCloseButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  tipsModalCloseButtonText: {
    fontSize: 16,
    color: '#9b59b6',
    fontWeight: '600',
  },
  workCheckModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  workCheckModalContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    width: '100%',
    maxWidth: 400,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  workCheckModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginBottom: 16,
    textAlign: 'center',
  },
  workCheckModalInput: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: '#2c3e50',
    minHeight: 120,
    marginBottom: 20,
    textAlignVertical: 'top',
  },
  workCheckModalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  workCheckCloseButton: {
    flex: 1,
    backgroundColor: '#e74c3c',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  workCheckCloseButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  workCheckSubmitButton: {
    flex: 1,
    backgroundColor: '#3498db',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  workCheckSubmitButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },

  // Routine Maintenance Screen Styles
  routineMaintenanceContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  routineMaintenanceHeader: {
    backgroundColor: '#3498db',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: HEADER_PADDING_TOP,
    paddingBottom: 16,
  },
  routineMaintenanceBackButton: {
    padding: 8,
  },
  routineMaintenanceTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    flex: 1,
    textAlign: 'center',
    marginHorizontal: 20,
  },
  routineMaintenanceHeaderSpacer: {
    width: 40,
  },
  routineMaintenanceContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  routineMaintenanceItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingVertical: 20,
    paddingHorizontal: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  routineMaintenanceItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  routineMaintenanceIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  routineMaintenanceItemText: {
    fontSize: 16,
    color: '#2c3e50',
    fontWeight: '500',
  },

  // AMC List Screen Styles
  amcListContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  amcListHeader: {
    backgroundColor: '#3498db',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: HEADER_PADDING_TOP,
    paddingBottom: 16,
  },
  amcListBackButton: {
    padding: 8,
  },
  amcListTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    flex: 1,
    textAlign: 'center',
    marginHorizontal: 20,
  },
  amcListSearchButton: {
    padding: 8,
  },
  amcListContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  amcListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  amcListItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  amcListIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#f8f9fa',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    position: 'relative',
  },
  amcListWrenchIcon: {
    position: 'absolute',
    bottom: 2,
    right: 2,
  },
  amcListItemDetails: {
    flex: 1,
  },
  amcListItemTitle: {
    fontSize: 16,
    color: '#2c3e50',
    fontWeight: '500',
    marginBottom: 4,
  },
  amcListItemSubtitle: {
    fontSize: 14,
    color: '#7f8c8d',
  },
  amcListStatusText: {
    fontWeight: '600',
  },

  // Customers Screen Styles
  customersContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  customersHeader: {
    backgroundColor: '#3498db',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: HEADER_PADDING_TOP,
    paddingBottom: 16,
  },
  customersBackButton: {
    padding: 8,
  },
  customersTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    flex: 1,
    textAlign: 'center',
    marginHorizontal: 20,
  },
  customersSearchButton: {
    padding: 8,
  },
  customersContent: {
    flex: 1,
    backgroundColor: '#fefefe',
  },
  customersItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  customersItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  customersIconContainer: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#f8f9fa',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  customersItemText: {
    fontSize: 16,
    color: '#2c3e50',
    fontWeight: '500',
    flex: 1,
  },
  customersSearchContainer: {
    backgroundColor: '#fff',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  customersSearchInput: {
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: '#2c3e50',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  amcListSearchContainer: {
    backgroundColor: '#fff',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  amcListSearchInput: {
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: '#2c3e50',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },

  // Tickets Screen Styles
  ticketsContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  ticketsHeader: {
    backgroundColor: '#3498db',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: HEADER_PADDING_TOP,
    paddingBottom: 16,
  },
  ticketsBackButton: {
    padding: 8,
  },
  ticketsTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    flex: 1,
    textAlign: 'center',
    marginHorizontal: 20,
  },
  ticketsHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ticketsSearchButton: {
    padding: 8,
    marginRight: 8,
  },
  ticketsFilterButton: {
    padding: 8,
  },
  ticketsSearchContainer: {
    backgroundColor: '#fff',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  ticketsSearchInput: {
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: '#2c3e50',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  ticketsContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  ticketsItem: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  ticketsMainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  ticketsMainRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  ticketsNotificationIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f8f9fa',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  ticketsMainRowContent: {
    flex: 1,
  },
  ticketsTitleText: {
    fontSize: 16,
    color: '#2c3e50',
    fontWeight: 'bold',
    marginBottom: 4,
  },
  ticketsDateTimeText: {
    fontSize: 14,
    fontWeight: '500',
  },
  ticketsExpandedContent: {
    paddingHorizontal: 16,
    paddingBottom: 16,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  ticketsDetailText: {
    fontSize: 14,
    color: '#2c3e50',
    marginBottom: 8,
    lineHeight: 20,
  },
  ticketsActionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
    gap: 12,
  },
  ticketsGoToDetailsButton: {
    flex: 1,
    backgroundColor: '#e74c3c',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  ticketsGoToDetailsButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  ticketsAssignButton: {
    flex: 1,
    backgroundColor: '#3498db',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  ticketsAssignButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },

  // Mark Attendance Screen Styles
  markAttendanceContainer: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  markAttendanceHeader: {
    backgroundColor: '#3498db',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: HEADER_PADDING_TOP,
    paddingBottom: 16,
  },
  markAttendanceBackButton: {
    padding: 8,
  },
  markAttendanceTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    flex: 1,
    textAlign: 'center',
    marginHorizontal: 20,
  },
  markAttendanceHeaderSpacer: {
    width: 40,
  },
  markAttendanceContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 40,
    alignItems: 'center',
  },
  markAttendanceCameraPreview: {
    width: '100%',
    height: 300,
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#2c3e50',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 40,
    position: 'relative',
  },
  markAttendancePreviewText: {
    fontSize: 16,
    color: '#7f8c8d',
    fontWeight: '500',
    textAlign: 'center',
  },
  markAttendanceSuccessIcon: {
    position: 'absolute',
    top: 20,
    right: 20,
  },
  markAttendanceButtons: {
    width: '100%',
    gap: 16,
  },
  markAttendanceTakeSelfieButton: {
    backgroundColor: '#3498db',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    shadowColor: '#3498db',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  markAttendanceSubmitButton: {
    backgroundColor: '#3498db',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    shadowColor: '#3498db',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  markAttendanceButtonDisabled: {
    backgroundColor: '#bdc3c7',
    shadowOpacity: 0.1,
  },
  markAttendanceButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
});
